//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballAccountant.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FootballAccountant.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FootballAccountant.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are currently owed £{0:n0} to cover the cancellation made for {1:dd/MM/yy}..
        /// </summary>
        public static string DueCancellationText {
            get {
                return ResourceManager.GetString("DueCancellationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You currently owe £{0:n0} to cover between {1:dd/MM/yy} and {2:dd/MM/yy} inclusively..
        /// </summary>
        public static string DuePaymentText {
            get {
                return ResourceManager.GetString("DuePaymentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\footballaccountant.json.
        /// </summary>
        public static string GoogleCredPath {
            get {
                return ResourceManager.GetString("GoogleCredPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\client_secret.json.
        /// </summary>
        public static string GoogleSecretPath {
            get {
                return ResourceManager.GetString("GoogleSecretPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jammyfitz.
        /// </summary>
        public static string GoogleUser {
            get {
                return ResourceManager.GetString("GoogleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jammyfitz@hotmail.com.
        /// </summary>
        public static string MasterEmailAddress {
            get {
                return ResourceManager.GetString("MasterEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no unclaimed cancellations!.
        /// </summary>
        public static string NoDueCancellation {
            get {
                return ResourceManager.GetString("NoDueCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no outstanding payments!.
        /// </summary>
        public static string NoDuePayment {
            get {
                return ResourceManager.GetString("NoDuePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no unsettled cancellations!.
        /// </summary>
        public static string NoUnsettledCancellations {
            get {
                return ResourceManager.GetString("NoUnsettledCancellations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to something.
        /// </summary>
        public static string PassPhrase {
            get {
                return ResourceManager.GetString("PassPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pzJNs/yMKt5GKSEzXl0g5Q==.
        /// </summary>
        public static string SmtpAgentDutyCode {
            get {
                return ResourceManager.GetString("SmtpAgentDutyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jammyfitz@hotmail.com.
        /// </summary>
        public static string SmtpAgentSine {
            get {
                return ResourceManager.GetString("SmtpAgentSine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 587.
        /// </summary>
        public static string SmtpPort {
            get {
                return ResourceManager.GetString("SmtpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smtp.live.com.
        /// </summary>
        public static string SmtpServer {
            get {
                return ResourceManager.GetString("SmtpServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1Y1QyPzAo58oKZKQrp0LXY2nAknxWeLXmaOE9tYoGsh4.
        /// </summary>
        public static string SpreadsheetId {
            get {
                return ResourceManager.GetString("SpreadsheetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string SpreadsheetRange {
            get {
                return ResourceManager.GetString("SpreadsheetRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://docs.google.com/spreadsheets/d/1Y1QyPzAo58oKZKQrp0LXY2nAknxWeLXmaOE9tYoGsh4/pubhtml.
        /// </summary>
        public static string SpreadsheetUrl {
            get {
                return ResourceManager.GetString("SpreadsheetUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are currently owed an unsettled cancellation of £{0:n0} to cover the cancellation made for {1:dd/MM/yy}..
        /// </summary>
        public static string UnsettledCancellationText {
            get {
                return ResourceManager.GetString("UnsettledCancellationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\repos\FootballAccountant\FootballAccountant\.
        /// </summary>
        public static string WorkingDir {
            get {
                return ResourceManager.GetString("WorkingDir", resourceCulture);
            }
        }
    }
}
